WATCH_FOLDER = "C:/Users/cabra/Downloads"
VAULT_FOLDER = "C:/Users/cabra/Obsidian/ChatGPTVault"
ARCHIVE_FOLDER = WATCH_FOLDER + "/processed"
INDEX_NOTE = VAULT_FOLDER + "/ChatGPT Summary Index.md"
LOG_FILE = VAULT_FOLDER + "/chatgpt_watcher.log"
